import type { Origin } from "../../shared/schema";

const TEXT: Record<Origin, { label: string; title: string }> = {
  ai: { label: "AI-generated", title: "Generated by Claude through the Driven Play Lab server. Review before using with players." },
  demo: { label: "DEMO sample", title: "Built-in sample content shown because the server has no AI key configured. Not AI-generated." },
  manual: { label: "Coach-made", title: "Created in the editor by a coach." },
};

export function OriginBadge({ origin }: { origin: Origin }) {
  const t = TEXT[origin];
  return (
    <span className={`badge badge--${origin}`} title={t.title}>
      {t.label}
    </span>
  );
}

export function DemoBanner() {
  return (
    <div className="demo-banner" role="status">
      <strong>Demo mode.</strong> The server has no AI key configured, so suggestions come from a small built-in sample
      library and plain-language changes are limited to simple edits (slower, faster, mirror, add a defender). Everything
      else — editing, playback, playbooks and share links — works normally.
    </div>
  );
}
