/**
 * Guardrail: generated content must not claim that a play comes from an NBA,
 * WNBA, college or USA Basketball program unless the source is verified.
 * Driven Play Lab has no source-verification pipeline yet, so every
 * generated activity is labeled as an original design and any sentence that
 * names such a program is removed before it reaches the coach.
 *
 * Generic concept names ("Horns", "Spain pick-and-roll", "motion offense")
 * are fine: they describe a structure, not who runs it.
 */
import type { Activity } from "./schema";

export const ORIGINAL_ATTRIBUTION =
  "Original design generated by Driven Play Lab. Not attributed to, or endorsed by, any NBA, WNBA, college or USA Basketball program.";

// Distinctive nicknames: matched whenever capitalized.
const NBA_TEAMS = [
  "Celtics", "Hornets", "Cavaliers", "Cavs", "Mavericks", "Mavs", "Nuggets", "Pistons", "Warriors",
  "Clippers", "Lakers", "Grizzlies", "Timberwolves", "Pelicans", "Knicks", "76ers", "Sixers",
  "Trail Blazers", "Spurs", "Raptors", "Wizards",
];
// Nicknames that are also everyday words ("heat", "magic", "nets"): only as "the X" or "X's".
const AMBIGUOUS_TEAMS = ["Hawks", "Nets", "Bulls", "Rockets", "Pacers", "Heat", "Bucks", "Thunder", "Magic", "Suns", "Blazers", "Kings", "Jazz"];

const PROGRAM_PATTERNS: RegExp[] = [
  /\bNBA\b/i,
  /\bWNBA\b/i,
  /\bG[- ]League\b/i,
  /\bNCAA\b/i,
  /\bUSA Basketball\b/i,
  /\bTeam USA\b/i,
  /\bOlympic team\b/i,
  /\b(?:college|university|collegiate) (?:program|team|coach(?:es)?|staff)\b/i,
  /\b(?:Duke|UConn|Kentucky|Kansas|North Carolina|Tar Heels|Villanova|Gonzaga|Michigan State|Syracuse|Virginia Cavaliers)\b/,
  new RegExp(`\\b(?:${NBA_TEAMS.join("|")})\\b`),
  new RegExp(`\\b[Tt]he (?:${AMBIGUOUS_TEAMS.join("|")})\\b`),
  new RegExp(`\\b(?:${AMBIGUOUS_TEAMS.join("|")})['’]`),
];

export function mentionsProgram(text: string): boolean {
  return PROGRAM_PATTERNS.some((re) => re.test(text));
}

/** Remove sentences that name a program; returns the cleaned text. */
export function stripProgramSentences(text: string): string {
  const sentences = text.match(/[^.!?]+[.!?]*\s*/g) ?? [text];
  return sentences
    .filter((s) => !mentionsProgram(s))
    .join("")
    .trim();
}

/**
 * Apply the attribution guardrail to every text field of an activity.
 * Returns the cleaned activity and notes describing what was removed.
 */
export function enforceAttribution(
  activity: Activity,
  attribution: string = ORIGINAL_ATTRIBUTION,
): { activity: Activity; notes: string[] } {
  const a: Activity = structuredClone(activity);
  let removed = 0;
  const clean = (s: string) => {
    if (!mentionsProgram(s)) return s;
    removed++;
    return stripProgramSentences(s);
  };
  const cleanList = (xs: string[]) => xs.map(clean).filter((s) => s.length > 0);

  a.title = clean(a.title) || "Untitled activity";
  a.summary = clean(a.summary);
  a.level = clean(a.level);
  a.objectives = cleanList(a.objectives);
  a.setup = cleanList(a.setup);
  a.instructions = cleanList(a.instructions);
  a.rotations = cleanList(a.rotations);
  a.coachingCues = cleanList(a.coachingCues);
  a.variations = cleanList(a.variations);
  a.equipment = cleanList(a.equipment);
  for (const p of a.players) if (p.name) p.name = clean(p.name) || null;
  for (const s of a.steps) {
    s.label = clean(s.label) || "Step";
    s.note = clean(s.note);
  }
  a.attribution = attribution;
  const notes = removed
    ? [`Removed ${removed} unverified reference(s) to a pro, college or national-team program.`]
    : [];
  return { activity: a, notes };
}
